[package]
name = "utreexo-wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustreexo = { git = "https://www.github.com/Davidson-Souza/rustreexo", branch = "drop_rust-bitcoin"}
btcd-rpc = { git = "https://github.com/Davidson-Souza/rust-btcd-rpc", features = ["utreexod"]}
clap = {version = "4.0.29", features = ["derive"]}
sha2 = "^0.10.6"
async-std = "1.12.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
timer = "0.2.0"
chrono = "0.4.23"
kv = "0.24.0"
bitcoin = {version = "0.29", features = ["serde", "std", "bitcoinconsensus"]}
miniscript = "9.0.0"
pretty_env_logger = "0.4.0"

[dev-dependencies]
# for random filenames in tests
rand = "0.8.5"